"""Standard workflow tests: build-db -> parameterize.

These tests run the full workflow end-to-end and store artifacts
in tests/standard/workflow_output for user review.
"""

import logging
import sys
from pathlib import Path

import pytest

from macromapff.cli import buildDb, parameterize


# Base path for test fixtures
FIXTURES = Path(__file__).parent / "standard"
SEG_DATA = FIXTURES / "segdata"
TARGET_DIR = FIXTURES / "target"
OUTPUT_DIR = FIXTURES / "workflow_output"


class TestStandardWorkflow:
    """End-to-end workflow tests."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Set up test output directory."""
        self.output_dir = OUTPUT_DIR
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.db_path = self.output_dir / "db.pkl"
        self.param_output = self.output_dir / "PS-oDMS7POSS_param.lmp"
        self.build_log = self.output_dir / "build-db.log"
        self.param_log = self.output_dir / "parameterize.log"

    def test_build_db(self):
        """Build database from standard segment data."""
        # Set up file handler for logging
        file_handler = logging.FileHandler(self.build_log, mode="w")
        file_handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s")
        file_handler.setFormatter(formatter)

        root_logger = logging.getLogger()
        original_level = root_logger.level
        root_logger.setLevel(logging.DEBUG)
        root_logger.addHandler(file_handler)

        try:
            result = buildDb(SEG_DATA, self.db_path, verbose=True)

            assert result["samples_count"] == 4
            assert result["atoms_processed"] == 302
            assert self.db_path.exists()
        finally:
            root_logger.removeHandler(file_handler)
            root_logger.setLevel(original_level)
            file_handler.close()

    def test_parameterize(self):
        """Parameterize target molecule using built database."""
        # First build the database
        buildDb(SEG_DATA, self.db_path, verbose=False)

        # Set up file handler for logging
        file_handler = logging.FileHandler(self.param_log, mode="w")
        file_handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s")
        file_handler.setFormatter(formatter)

        root_logger = logging.getLogger()
        original_level = root_logger.level
        root_logger.setLevel(logging.DEBUG)
        root_logger.addHandler(file_handler)

        try:
            # Parameterize target
            mol_path = TARGET_DIR / "PS-oDMS7POSS.mol"
            result = parameterize(mol_path, self.db_path, self.param_output, verbose=True)

            # Verify output
            assert result["atoms"] == 3313
            assert result["bonds"] == 3486
            assert result["angles"] > 0
            assert result["dihedrals"] > 0
            assert result["impropers"] > 0
            assert result["unique_types"] == 51
            assert result["hop2_matches"] == 3312
            assert result["hop1_matches"] == 1
            assert result["hop0_matches"] == 0
            assert result["no_match"] == 0

            # Verify output file exists and has content
            assert self.param_output.exists()
            assert self.param_output.stat().st_size > 400000  # ~400KB
        finally:
            root_logger.removeHandler(file_handler)
            root_logger.setLevel(original_level)
            file_handler.close()

    def test_output_lammps_format(self):
        """Verify output LAMMPS file has correct format."""
        buildDb(SEG_DATA, self.db_path, verbose=False)

        mol_path = TARGET_DIR / "PS-oDMS7POSS.mol"
        parameterize(mol_path, self.db_path, self.param_output, verbose=False)

        content = self.param_output.read_text()

        # Check header
        assert "LAMMPS data file Generated by MacroMapFF" in content

        # Check section counts
        assert "3313 atoms" in content
        assert "3486 bonds" in content
        assert "6244 angles" in content
        assert "9638 dihedrals" in content
        assert "1014 impropers" in content

        # Check type counts
        assert "51 atom types" in content
        assert "18 bond types" in content
        assert "31 angle types" in content
        assert "26 dihedral types" in content
        assert "3 improper types" in content

        # Check sections exist
        assert "Masses" in content
        assert "Pair Coeffs" in content
        assert "Bond Coeffs" in content
        assert "Angle Coeffs" in content
        assert "Dihedral Coeffs" in content
        assert "Improper Coeffs" in content
        assert "Atoms" in content
        assert "Bonds" in content
        assert "Angles" in content
        assert "Dihedrals" in content
        assert "Impropers" in content