"""Standard workflow tests: build-db -> parameterize via CLI."""

import logging
import os
import sys
from pathlib import Path
from unittest.mock import patch

# Base path for test fixtures
FIXTURES = Path(__file__).parent / "standard"
SEG_DATA = FIXTURES / "samples"
TARGET_FILE = FIXTURES / "target.mol"
DB_PATH = FIXTURES / "samples.db"


class TestStandardWorkflow:
    """End-to-end workflow tests via CLI."""

    def test_full_workflow(self):
        """Run the complete build-db -> parameterize workflow end-to-end."""
        # Ensure we're in the project root
        os.chdir(Path(__file__).parent.parent.parent)

        # Clean up outputs
        if DB_PATH.exists():
            DB_PATH.unlink()
        target_lmp = FIXTURES / "target.lmp"
        if target_lmp.exists():
            target_lmp.unlink()

        # Step 1: build-db
        # Clean up logging handlers from previous calls
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)

        build_args = [
            "mappingff",
            "build-db",
            str(SEG_DATA),
            "-d",
            str(DB_PATH),
        ]
        with patch.object(sys, "argv", build_args):
            from mappingff.cli import main

            main()

        assert DB_PATH.exists()

        # Step 2: parameterize
        # Clean up logging handlers from previous calls
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)

        param_args = [
            "mappingff",
            "parameterize",
            str(TARGET_FILE),
            "-d",
            str(DB_PATH),
            "-o",
            str(target_lmp),
            "-v",
        ]
        with patch.object(sys, "argv", param_args):
            main()

        # Verify output file exists and has content
        assert target_lmp.exists()
        assert target_lmp.stat().st_size > 400000

        # Verify output file content
        content = target_lmp.read_text()

        # Check header
        assert "LAMMPS data file Generated by mappingff" in content

        # Check section counts
        assert "3313 atoms" in content
        assert "3486 bonds" in content
        assert "6245 angles" in content
        assert "9652 dihedrals" in content
        assert "1014 impropers" in content

        # Check type counts
        assert "73 atom types" in content
        assert "18 bond types" in content
        assert "31 angle types" in content
        assert "26 dihedral types" in content
        assert "3 improper types" in content

        # Check sections exist
        assert "Masses" in content
        assert "Pair Coeffs" in content
        assert "Bond Coeffs" in content
        assert "Angle Coeffs" in content
        assert "Dihedral Coeffs" in content
        assert "Improper Coeffs" in content
        assert "Atoms" in content
        assert "Bonds" in content
        assert "Angles" in content
        assert "Dihedrals" in content
        assert "Impropers" in content
