"""Standard workflow tests: build-db -> parameterize."""

import logging
from pathlib import Path

import pytest

from mappingff.workflow import buildDb, parameterize

# Base path for test fixtures
FIXTURES = Path(__file__).parent / "standard"
SEG_DATA = FIXTURES / "samples"
TARGET_FILE = FIXTURES / "target.mol"


class TestStandardWorkflow:
    """End-to-end workflow tests."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Set up output paths under FIXTURES directory."""
        self.db_path = FIXTURES / "samples.db"
        self.build_log = FIXTURES / "build-db.log"
        self.param_log = FIXTURES / "parameterize.log"

    def test_full_workflow(self):
        """Run the complete build-db -> parameterize workflow end-to-end."""
        # Set up file handler for build-db logging
        build_handler = logging.FileHandler(self.build_log, mode="w")
        build_handler.setLevel(logging.DEBUG)
        build_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))
        root_logger = logging.getLogger()
        original_level = root_logger.level
        root_logger.setLevel(logging.DEBUG)
        root_logger.addHandler(build_handler)

        try:
            # Step 1: Build database
            result = buildDb(SEG_DATA, self.db_path, verbose=True)
            assert result["samples_count"] == 4
            assert result["atoms_processed"] == 318
            assert self.db_path.exists()
        finally:
            root_logger.removeHandler(build_handler)
            root_logger.setLevel(original_level)
            build_handler.close()

        # Set up file handler for parameterize logging
        param_handler = logging.FileHandler(self.param_log, mode="w")
        param_handler.setLevel(logging.DEBUG)
        param_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))
        root_logger = logging.getLogger()
        root_logger.setLevel(logging.DEBUG)
        root_logger.addHandler(param_handler)

        try:
            # Step 2: Parameterize target molecule using built database
            result = parameterize(TARGET_FILE, self.db_path, verbose=True)

            # Verify parameterization results
            assert result["atoms"] == 3313
            assert result["bonds"] == 3486
            assert result["angles"] > 0
            assert result["dihedrals"] > 0
            assert result["impropers"] > 0
            assert result["unique_types"] == 37
            assert result["hop3_matches"] == 2536
            assert result["hop2_matches"] == 543
            assert result["hop1_matches"] == 234
            assert result["hop0_matches"] == 0
            assert result["no_match"] == 0

            # Verify output file exists and has content
            param_out = FIXTURES / "target.lmp"
            assert param_out.exists()
            assert param_out.stat().st_size > 400000

            # Step 3: Verify LAMMPS file format
            content = param_out.read_text()

            # Check header
            assert "LAMMPS data file Generated by mappingff" in content

            # Check section counts
            assert "3313 atoms" in content
            assert "3486 bonds" in content
            assert "6245 angles" in content
            assert "9652 dihedrals" in content
            assert "2973 impropers" in content

            # Check type counts
            assert "37 atom types" in content
            assert "18 bond types" in content
            assert "31 angle types" in content
            assert "26 dihedral types" in content
            assert "3 improper types" in content

            # Check sections exist
            assert "Masses" in content
            assert "Pair Coeffs" in content
            assert "Bond Coeffs" in content
            assert "Angle Coeffs" in content
            assert "Dihedral Coeffs" in content
            assert "Improper Coeffs" in content
            assert "Atoms" in content
            assert "Bonds" in content
            assert "Angles" in content
            assert "Dihedrals" in content
            assert "Impropers" in content
        finally:
            root_logger.removeHandler(param_handler)
            root_logger.setLevel(original_level)
            param_handler.close()
