"""Standard workflow tests: build-db -> parameterize via CLI."""

import logging
import sys
from pathlib import Path
from unittest.mock import patch

# Base path for test fixtures
FIXTURES = Path(__file__).parent / "standard"
SEG_DATA = FIXTURES / "samples"
TARGET_FILE = FIXTURES / "50_ps_50_pmma.mol"


class TestStandardWorkflow:
    """End-to-end workflow tests via CLI."""

    def test_full_workflow(self, tmp_path):
        """Run the complete build-db -> parameterize workflow end-to-end."""
        db_path = tmp_path / "samples.db"
        target_lmp = tmp_path / "target.lmp"

        # Step 1: build-db
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)

        build_args = [
            "mappingff",
            "build-db",
            str(SEG_DATA),
            "-d",
            str(db_path),
        ]
        with patch.object(sys, "argv", build_args):
            from mappingff.cli import main

            main()

        assert db_path.exists()

        # Step 2: parameterize
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)

        param_args = [
            "mappingff",
            "parameterize",
            str(TARGET_FILE),
            "-d",
            str(db_path),
            "-o",
            str(target_lmp),
            "-v",
        ]
        with patch.object(sys, "argv", param_args):
            main()

        # Verify output file exists and has content
        assert target_lmp.exists()
        assert target_lmp.stat().st_size > 600000

        content = target_lmp.read_text()

        # Check header
        assert "LAMMPS data file Generated by mappingff" in content

        # Check section counts
        assert "1552 atoms" in content
        assert "1601 bonds" in content
        assert "2900 angles" in content
        assert "4291 dihedrals" in content
        assert "350 impropers" in content

        # Check type counts
        assert "45 atom types" in content
        assert "9 bond types" in content
        assert "13 angle types" in content
        assert "12 dihedral types" in content
        assert "2 improper types" in content

        # Check sections exist
        assert "Masses" in content
        assert "Pair Coeffs" in content
        assert "Bond Coeffs" in content
        assert "Angle Coeffs" in content
        assert "Dihedral Coeffs" in content
        assert "Improper Coeffs" in content
        assert "Atoms" in content
        assert "Bonds" in content
        assert "Angles" in content
        assert "Dihedrals" in content
        assert "Impropers" in content