#!/usr/bin/env python3
from pathlib import Path


def _fmt_box(lo, hi):
    return f"{lo:12.6f} {hi:12.6f}"


def write_lammps_data(
    out_path: Path,
    mol,
    atom_records,
    atom_type_rows,
    bond_records,
    angle_records,
    dihedral_records,
    improper_records,
    bond_type_rows,
    angle_type_rows,
    dihedral_type_rows,
    improper_type_rows,
    molecule_id: int,
    box_padding: float,
):
    conf = mol.GetConformer()
    xs, ys, zs = [], [], []
    for i in range(mol.GetNumAtoms()):
        p = conf.GetAtomPosition(i)
        xs.append(float(p.x))
        ys.append(float(p.y))
        zs.append(float(p.z))

    xlo, xhi = min(xs) - box_padding, max(xs) + box_padding
    ylo, yhi = min(ys) - box_padding, max(ys) + box_padding
    zlo, zhi = min(zs) - box_padding, max(zs) + box_padding

    atom_by_id = {a["atom_id"]: a for a in atom_records}

    improper_has_zero = any(int(r.get("type_id", 0)) == 0 for r in improper_records)
    if improper_has_zero:
        improper_records_out = []
        for rec in improper_records:
            rec_new = dict(rec)
            rec_new["type_id"] = max(1, int(rec_new.get("type_id", 0)))
            improper_records_out.append(rec_new)
        improper_type_rows_out = improper_type_rows
    else:
        improper_records_out = improper_records
        improper_type_rows_out = improper_type_rows

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("LAMMPS data file generated by lammps_gen.py\n\n")
        f.write(f"{len(atom_records):8d} atoms\n")
        f.write(f"{len(bond_records):8d} bonds\n")
        f.write(f"{len(angle_records):8d} angles\n")
        f.write(f"{len(dihedral_records):8d} dihedrals\n")
        f.write(f"{len(improper_records_out):8d} impropers\n\n")

        f.write(f"{len(atom_type_rows):8d} atom types\n")
        f.write(f"{len(bond_type_rows):8d} bond types\n")
        f.write(f"{len(angle_type_rows):8d} angle types\n")
        f.write(f"{len(dihedral_type_rows):8d} dihedral types\n")
        f.write(f"{len(improper_type_rows_out):8d} improper types\n\n")

        f.write(f"{_fmt_box(xlo, xhi)} xlo xhi\n")
        f.write(f"{_fmt_box(ylo, yhi)} ylo yhi\n")
        f.write(f"{_fmt_box(zlo, zhi)} zlo zhi\n\n")

        f.write("Masses\n\n")
        for row in atom_type_rows:
            f.write(f"{row['local_type']:8d} {row['mass']:10.6f}\n")
        f.write("\n")

        f.write("Pair Coeffs\n\n")
        for row in atom_type_rows:
            f.write(
                f"{row['local_type']:8d} {row['epsilon']:10.6f} {row['sigma']:10.6f}\n"
            )
        f.write("\n")

        f.write("Bond Coeffs\n\n")
        for tid, coeff in bond_type_rows:
            f.write(f"{tid:8d} " + " ".join(f"{float(x):10.4f}" for x in coeff) + "\n")
        f.write("\n")

        f.write("Angle Coeffs\n\n")
        for tid, coeff in angle_type_rows:
            f.write(f"{tid:8d} " + " ".join(f"{float(x):10.3f}" for x in coeff) + "\n")
        f.write("\n")

        f.write("Dihedral Coeffs\n\n")
        for tid, coeff in dihedral_type_rows:
            f.write(f"{tid:8d} " + " ".join(f"{float(x):10.3f}" for x in coeff) + "\n")
        f.write("\n")

        f.write("Improper Coeffs\n\n")
        for tid, coeff in improper_type_rows_out:
            f.write(
                f"{tid:8d} {float(coeff[0]):10.3f} {int(float(coeff[1])):7d} {int(float(coeff[2])):7d}\n"
            )
        f.write("\n")

        f.write("Atoms\n\n")
        for atom_id in range(1, mol.GetNumAtoms() + 1):
            p = conf.GetAtomPosition(atom_id - 1)
            rec = atom_by_id[atom_id]
            f.write(
                f"{atom_id:8d} {molecule_id:6d} {rec['atom_type']:6d} "
                f"{rec['charge']:10.6f} {float(p.x):10.5f} {float(p.y):10.5f} {float(p.z):10.5f}\n"
            )
        f.write("\n")

        f.write("Bonds\n\n")
        for idx, rec in enumerate(bond_records, start=1):
            i, j = rec["atom_ids"]
            f.write(f"{idx:8d} {rec['type_id']:6d} {i:6d} {j:6d}\n")
        f.write("\n")

        f.write("Angles\n\n")
        for idx, rec in enumerate(angle_records, start=1):
            i, j, k = rec["atom_ids"]
            f.write(f"{idx:8d} {rec['type_id']:6d} {i:6d} {j:6d} {k:6d}\n")
        f.write("\n")

        f.write("Dihedrals\n\n")
        for idx, rec in enumerate(dihedral_records, start=1):
            i, j, k, l = rec["atom_ids"]
            f.write(f"{idx:8d} {rec['type_id']:6d} {i:6d} {j:6d} {k:6d} {l:6d}\n")
        f.write("\n")

        f.write("Impropers\n\n")
        for idx, rec in enumerate(improper_records_out, start=1):
            i, j, k, l = rec["atom_ids"]
            f.write(f"{idx:8d} {rec['type_id']:6d} {i:6d} {j:6d} {k:6d} {l:6d}\n")
